# Generated by Django 5.1.3 on 2024-11-23 10:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('image_slider', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Main image of the slider', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the label of the link', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Select the type of link'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select an internal page', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter an external URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('link_type', 3), ('internal_page', 4), ('external_url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add button section', 'label': 'Add link details', 'max_num': 2, 'min_num': 0}), 8: ('wagtail.blocks.StructBlock', [[('main_title', 0), ('main_image', 1), ('description', 0), ('links', 7)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(default='main_title', max_length=100),
            preserve_default=False,
        ),
    ]
