# Generated by Django 5.1.3 on 2024-11-23 10:33

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Please enter name', max_length=250)),
                ('disclaimer', wagtail.fields.RichTextField(blank=True, help_text='Please enter disclaimer')),
                ('copyright', wagtail.fields.RichTextField(blank=True, help_text='Please enter copyright')),
                ('social_media', wagtail.fields.StreamField([('social_media', 3)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('google_plus', 'GooglePlus')]}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('icon', 1), ('url', 2)]], {})})),
                ('contact_content', wagtail.fields.StreamField([('contact_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.EmailBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('locations', 0), ('phone_number', 0), ('email', 1)]], {})})),
                ('new_letter_content', wagtail.fields.StreamField([('new_letter_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})})),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
