# Generated by Django 5.1.3 on 2024-11-23 10:33

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Please enter name', max_length=255)),
                ('nav_type', models.CharField(blank=True, choices=[('header', 'Header Navigation'), ('footer', 'Footer Navigation'), ('footer_links', 'Footer Links')], default='top', help_text='Navigation type', max_length=20, null=True)),
                ('menus', wagtail.fields.StreamField([('single_menu', 7), ('multiple_menu', 9), ('tabbed_menu', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please enter menu name', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('text', 'Text Menu'), ('bordered_button', 'Bordered Button Menu'), ('filled_button', 'Filled Button Menu')], 'help_text': 'Menu type', 'max_length': 20, 'null': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')]}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'editable': False, 'help_text': 'This field can be avoided and will be set automatically.', 'label': 'Page name(internal)', 'max_length': 150, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('link_type', 3), ('external_url', 4), ('internal_page_model_name', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('menu_type', 1), ('menu_item', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (6,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('menu_type', 1), ('menu_items', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please enter tab name', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please enter tab name', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please provide unique slug name for url', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('slug', 12), ('menu_items', 8)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 10), ('tabs', 14)]], {})})),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
